config/routes.rb
Rails.application.routes.draw do
  resources :autos
  root "autos#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auto.rb
class Auto < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/autos_controller.rb
class AutosController < ApplicationController
  before_action :set_auto, only: [:show, :edit, :update, :destroy]

  # GET /autos
  # GET /autos.json
  def index
    @autos = Auto.all
  end

  # GET /autos/1
  # GET /autos/1.json
  def show
  end

  # GET /autos/new
  def new
    @auto = Auto.new
  end

  # GET /autos/1/edit
  def edit
  end

  # POST /autos
  # POST /autos.json
  def create
    @auto = Auto.new(auto_params)

    respond_to do |format|
      if @auto.save
        format.html { redirect_to @auto, notice: 'Auto was successfully created.' }
        format.json { render :show, status: :created, location: @auto }
      else
        format.html { render :new }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /autos/1
  # PATCH/PUT /autos/1.json
  def update
    respond_to do |format|
      if @auto.update(auto_params)
        format.html { redirect_to @auto, notice: 'Auto was successfully updated.' }
        format.json { render :show, status: :ok, location: @auto }
      else
        format.html { render :edit }
        format.json { render json: @auto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /autos/1
  # DELETE /autos/1.json
  def destroy
    @auto.destroy
    respond_to do |format|
      format.html { redirect_to autos_url, notice: 'Auto was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_auto
      @auto = Auto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def auto_params
      params.require(:auto).permit(:name, :modelo, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/autos_helper.rb
module AutosHelper
end

app/views/autos/_form.html.erb
<%= form_with(model: auto, local: true) do |form| %>
  <% if auto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(auto.errors.count, "error") %> prohibited this auto from being saved:</h2>

      <ul>
      <% auto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :auto_name %>
  </div>

  <div class="field">
    <%= form.label :modelo %>
    <%= form.text_field :modelo, id: :auto_modelo %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo, id: :auto_photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/autos/edit.html.erb
<h1>Editing Auto</h1>

<%= render 'form', auto: @auto %>

<%= link_to 'Show', @auto %> |
<%= link_to 'Back', autos_path %>

app/views/autos/index.html.erb
<p id="notice" xmlns:margin-bottom="http://www.w3.org/1999/xhtml" xmlns:margin-bottom="http://www.w3.org/1999/xhtml"
   xmlns:margin-bottom="http://www.w3.org/1999/xhtml"><%= notice %></p>
<div>
  <marquee><h1>Classic Car</h1></marquee>
</div>
<div class="grid">


  <% @autos.each do|auto|%>
      <div class="grid-item" style="width: 25%">
        <div class="thumbnail">
          <%= auto.name %>
          <%= auto.modelo %>
          <%= image_tag(auto.photo, :class => 'img-responsive') %>
          <div class="buttons", style="margin-top:10px; margin-bottom:10px ">
            <%=link_to 'Show', auto, :class => 'btn' %>
            <%=link_to 'Edit',  edit_auto_path(auto), :class => 'btn'%>
            <%=link_to 'Destroy',  auto, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn'%>
          </div>
      </div>
        <%=link_to 'New Auto', new_auto_path %>
</div>

  <% end %>
<br>

</div>

<script type="text/javascript">
    var elem = document.querySelector('.grid');
    var msnry = new Masonry( elem, {
        // options
        itemSelector: '.grid-item',
        columnWidth: 200
    });
    $(window).load(function(){
        var elem = document.querySelector('.grid');
        var msnry = new Masonry( elem, {
            // options
            itemSelector: '.grid-item',
            columnWidth: 200
        });
    })
</script>

app/views/autos/new.html.erb
<h1>New Auto</h1>

<%= render 'form', auto: @auto %>

<%= link_to 'Back', autos_path %>

app/views/autos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @auto.name %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @auto.modelo %>
</p>

<p>
  <strong>Photo:</strong>
  <%= image_tag(@auto.photo, :style => 'width:200px')%>
</p>

<%= link_to 'Edit', edit_auto_path(@auto) %> |
<%= link_to 'Back', autos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyAutos</title>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">


  <%= stylesheet_link_tag    '/assets/application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag '/assets/application', 'data-turbolinks-track': 'reload' %>



  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <script src="https://unpkg.com/masonry-layout@4/dist/masonry.pkgd.js"></script>
</head>

<body>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>
<%= yield %>
</body>
</html>